# Site settings
title: Wikipedia Rating Project
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Providing the tools for subject area experts to quickly and easily
  rate the reliability and accuracy of Wikipedia articles.
baseurl: /wikipedia-rating-project
url: "http://mjbuckley.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  mjbuckley

# Build settings
markdown: kramdown
